# Generated by Django 3.1.5 on 2021-03-28 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210328_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maillist',
            name='token',
            field=models.CharField(max_length=256, null=True, unique=True),
        ),
    ]
