# Generated by Django 3.1.5 on 2021-03-28 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210328_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maillist',
            name='token',
            field=models.CharField(max_length=1000, null=True, unique=True),
        ),
    ]
