# Generated by Django 3.1.5 on 2021-01-08 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benefits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='benefit',
            name='img_file',
            field=models.CharField(default=None, max_length=2048),
            preserve_default=False,
        ),
    ]
