# Generated by Django 3.1.5 on 2021-01-09 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benefits', '0002_benefit_img_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='benefit',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
