# Generated by Django 3.1.5 on 2021-01-16 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benefits', '0003_benefit_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefit',
            name='img_file',
            field=models.CharField(blank=True, max_length=2048),
        ),
    ]
