# Generated by Django 3.1.5 on 2021-01-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benefits', '0004_auto_20210116_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='benefit',
            name='highlights',
            field=models.JSONField(default=list),
        ),
    ]
