# Generated by Django 3.1.5 on 2021-01-22 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('benefits', '0005_benefit_highlights'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='benefit',
            name='is_verified',
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('contribution', models.JSONField()),
                ('approved', models.BooleanField(default=False)),
                ('benefit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='benefits.benefit')),
            ],
        ),
    ]
