# Generated by Django 3.1.5 on 2021-01-23 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('benefits', '0006_auto_20210122_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('last_sent_time', models.DateTimeField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterField(
            model_name='contribution',
            name='benefit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='benefits.benefit'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
