# Generated by Django 3.1.5 on 2021-01-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benefits', '0007_auto_20210123_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='maillist',
            name='token',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
