# Generated by Django 3.1.5 on 2021-03-30 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benefits', '0009_delete_maillist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefit',
            name='highlights',
            field=models.JSONField(),
        ),
    ]
